AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation Custom Resource for provisioning and validating an ACM certificate.

Resources:
    ACMRegisterFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: acm_register/
            Handler: app.handler
            Runtime: python3.7
            Timeout: 900
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - acm:RequestCertificate
                      - acm:DescribeCertificate
                      - acm:ListCertificates
                    Resource: '*'
                  - Effect: Allow
                    Action:
                      - route53:ChangeResourceRecordSets
                      - route53:ListHostedZonesByName
                    Resource: '*'
                  - Effect: Allow
                    Action:
                      - lambda:AddPermission
                      - lambda:RemovePermission
                      - events:PutRule
                      - events:DeleteRule
                      - events:PutTargets
                      - events:RemoveTargets
                    Resource: '*'

Outputs:
    ACMRegisterFunction:
      Description: "ARN for ACM Register custom resource function"
      Value: !GetAtt ACMRegisterFunction.Arn
      Export:
        Name: "ACMRegisterFunction"
