AWSTemplateFormatVersion: '2010-09-09'
Description: Example template for using the ACM custom resource
Parameters:
  DOMAIN:
    Type: String
    Description: Domain used for certificate
  RECORD:
    Type: String
    Description: Record used for certificate

Resources:
    ACMCertificate:
      Type: 'Custom::ACMCertificate'
      Version: '1.0'
      Properties:
        ServiceToken: !ImportValue ACMRegisterFunction
        Region: !Ref "AWS::Region"
        HostedZoneName: !Ref DOMAIN
        RecordName: !Ref RECORD
